# Generated by Django 5.2 on 2025-05-17 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_profile_nickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="avatar",
            new_name="_avatar",
        ),
    ]
