# Generated by Django 5.2 on 2025-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_avatar_profile__avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="_avatar",
            new_name="avatar",
        ),
    ]
